### ISSUE TITLE
Accessibility Checklist

### ISSUE THREAD

**Issue by kellycesario** [xossiane/javascript-oceandex#23]
- [x] Accessible arrows
- [x] Are there descriptive alts on all images with meaning/with links to another page?
- [x] Check the contrast between the background and the foreground
- [ ] Are the same clickable functions available via keyboard access?
